catalogMode: prefer

ignoreWorkspaceRootCheck: true

shellEmulator: true

trustPolicy: no-downgrade
packages:
  - playground
  - docs
  - packages/*
  - examples/*
catalog:
  '@hapi/boom': ^10.0.1
  '@types/qrcode-terminal': ^0.12.0
  '@types/ws': ^8.18.1
  '@whiskeysockets/baileys': 7.0.0-rc.9
  c12: ^3.3.0
  citty: ^0.2.0
  consola: ^3.2.3
  cron-parser: ^4.9.0
  crossws: v0.2.4
  defu: ^6.1.4
  destr: ^2.0.2
  ofetch: ^1.5.0
  pathe: ^2.0.0
  pino: 9.11.0
  qrcode-terminal: ^0.12.0
  ws: ^8.19.0
catalogs:
  cli:
    '@antfu/eslint-config': ^6.6.1
    '@antfu/ni': ^28.0.0
    '@clack/prompts': ^1.0.0
    bumpp: ^10.3.2
    eslint: ^9.39.2
    lint-staged: ^16.2.7
    publint: ^0.3.16
    simple-git-hooks: ^2.13.1
    tsdown: ^0.17.3
    tsx: ^4.21.0
    typescript: ^5.9.3
    vite: ^7.2.7
  inlined:
    '@antfu/utils': ^9.3.0
  skills:
    skills: ^1.3.4
    skills-manifest: ^0.3.2
  testing:
    tinyexec: ^1.0.2
    vitest: ^4.0.15
    vitest-package-exports: ^0.1.1
    yaml: ^2.8.2
  types:
    '@types/node': ^25.0.1
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
